sudo: required

services:
  - docker

language: java
dist: trusty

script:
  - mvn clean package -U
  - docker build -t ancina/user-stat .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ancina/user-stat