kumuluzee:
  name: user-stat-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8087
    http:
      port: 8087
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000

rest-config:
  string-property: Monday
  boolean-property: true
  integer-property: 23